DROP TABLE IF EXISTS INVEST_ORDER CASCADE;
DROP TABLE IF EXISTS INVEST_USER CASCADE;
DROP TABLE IF EXISTS INVEST_ORDER_ITEM CASCADE;
DROP TABLE IF EXISTS INVEST_PRODUCT CASCADE;

CREATE TABLE INVEST_USER (
                             ID bigint generated by default as identity,
                             EMAIL varchar(255),
                             NAME varchar(255),
                             primary key (ID)
);

CREATE TABLE INVEST_PRODUCT (
                                ID bigint generated by default as identity,
                                FINISHED_AT timestamp,
                                STARTED_AT timestamp,
                                STATE varchar(255),
                                TITLE varchar(255),
                                TOTAL_AMOUNT bigint,
                                primary key (ID)
);

CREATE TABLE INVEST_ORDER (
                              ID bigint generated by default as identity,
                              FINISHED_AT timestamp,
                              STARTED_AT timestamp,
                              STATE varchar(255),
                              USER_ID bigint,
                              primary key (ID),
                              CONSTRAINT FK_ORDER_TO_USER FOREIGN KEY (USER_ID) REFERENCES INVEST_USER (ID)
);

CREATE TABLE INVEST_ORDER_ITEM (
                                   ID bigint generated by default as identity,
                                   AMOUNT bigint,
                                   STATE varchar(255),
                                   ORDER_ID bigint,
                                   PRODUCT_ID bigint,
                                   primary key (ID),
                                   CONSTRAINT FK_ORDER_ITEM_TO_ORDER FOREIGN KEY (ORDER_ID) REFERENCES INVEST_ORDER (ID),
                                   CONSTRAINT FK_ORDER_ITEM_TO_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES INVEST_PRODUCT (ID)
);
